### ISSUE TITLE
How to use harmony

### ISSUE THREAD

**Issue by LiuXiaoxuanPKU** [msr-fiddle/harmony#1]
Thanks for the great work! Before navigating through the code base, I'm wondering if harmony provides an easy way to play with, for example:
```
import harmony

model = GPT2()
optimized_model = harmony.optimize(model) # run the profile, schedule, and generate the new DAG

# The original training loop on optmized_model
```
It will be beneficial to have the API to play with.

Thanks!

**Comment by leonardo0lyj** [comment]
Greetings @LiuXiaoxuanPKU : )

Great suggestion! I believe I can include it in a future version. 

Thanks > _ <
